// ═══════════════════════════════════════════════════════════════════════════
//  SENTINEL v3.0 — Endpoint Security Platform — PART 1/2
//  Run: powershell -File build.ps1 to assemble server.js from both parts
// ═══════════════════════════════════════════════════════════════════════════
const http=require('http');const{execFile}=require('child_process');const path=require('path');const fs=require('fs');const crypto=require('crypto');
const CONFIG_FILE=path.join(__dirname,'sentinel.config.json');
const DEFAULT_CONFIG={port:8888,host:'127.0.0.1',suricataEvePath:'C:\\ProgramData\\Suricata\\log\\eve.json',maxBodySize:4096,suricataMaxReadBytes:2*1024*1024,rateLimitWindowMs:60000,rateLimitMaxActions:30,fimEnabled:true,canaryEnabled:true,autoResponseEnabled:true,hardeningEnabled:true,threatIntelEnabled:true,usbMonitorEnabled:true,behavioralEnabled:true,scannerEnabled:true,fimIntervalMinutes:5,canaryDir:null,threatIntelFeeds:['https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt']};
function loadConfig(){let cfg={...DEFAULT_CONFIG};try{if(fs.existsSync(CONFIG_FILE))cfg={...cfg,...JSON.parse(fs.readFileSync(CONFIG_FILE,'utf8'))};else fs.writeFileSync(CONFIG_FILE,JSON.stringify(DEFAULT_CONFIG,null,2),'utf8');}catch(e){log('WARN','Config load failed',{error:e.message});}return cfg;}
const config=loadConfig();
const TOKEN_FILE=path.join(__dirname,'.sentinel-token');
function getOrCreateToken(){try{if(fs.existsSync(TOKEN_FILE)){const t=fs.readFileSync(TOKEN_FILE,'utf8').trim();if(t.length>=32)return t;}}catch{}const token=crypto.randomBytes(32).toString('hex');try{fs.writeFileSync(TOKEN_FILE,token,{encoding:'utf8',mode:0o600});}catch{}return token;}
const API_TOKEN=getOrCreateToken();
const LOG_FILE=path.join(__dirname,'sentinel.log');
function log(level,msg,data={}){const entry=JSON.stringify({ts:new Date().toISOString(),level,msg,...data});console.log(entry);try{fs.appendFileSync(LOG_FILE,entry+'\n');}catch{}}
const actionTimestamps=[];function isRateLimited(){const now=Date.now();while(actionTimestamps.length&&actionTimestamps[0]<now-config.rateLimitWindowMs)actionTimestamps.shift();if(actionTimestamps.length>=config.rateLimitMaxActions)return true;actionTimestamps.push(now);return false;}
function psExec(cmd,timeout=12000){return new Promise(resolve=>{execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',cmd],{timeout,windowsHide:true},(err,stdout)=>{if(err)log('WARN','PS fail',{cmd:cmd.substring(0,60),error:err.message});resolve(stdout?stdout.trim():'');});});}
function psJSON(cmd,timeout=12000,fallback={}){return new Promise(resolve=>{execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',cmd],{timeout,windowsHide:true},(err,stdout)=>{if(err){resolve(Array.isArray(fallback)?[...fallback]:{...fallback,_error:true});return;}try{let d=JSON.parse(stdout||JSON.stringify(fallback));if(Array.isArray(fallback)&&!Array.isArray(d))d=[d];resolve(d);}catch{resolve(Array.isArray(fallback)?[...fallback]:{...fallback,_error:true});}});});}
function isValidPid(pid){const n=parseInt(pid);return Number.isInteger(n)&&n>=100&&n<=65535;}
function isValidPort(port){const n=parseInt(port);return Number.isInteger(n)&&n>=1&&n<=65535;}
function portRisk(port,addr){const local=addr==='127.0.0.1'||addr==='::1';const crit=[445,139,135,3389,23,21,25].includes(port);const high=[80,8080,8443,22].includes(port);if(crit&&!local)return'CRITIQUE';if(crit)return'MOYEN';if(high&&!local)return'MOYEN';if(!local)return'FAIBLE';return'OK';}
async function getDefender(){return psJSON("Get-MpComputerStatus|Select-Object AntivirusEnabled,RealTimeProtectionEnabled,BehaviorMonitorEnabled,AntivirusSignatureLastUpdated,AntivirusSignatureVersion|ConvertTo-Json -Compress",10000,{});}
async function getFirewall(){return psJSON("Get-NetFirewallProfile|Select-Object Name,Enabled,DefaultInboundAction|ConvertTo-Json -Compress",10000,[]);}
async function getPorts(){const cmd="$r=foreach($c in (Get-NetTCPConnection -State Listen|Sort-Object LocalPort)){$p=Get-Process -Id $c.OwningProcess -EA SilentlyContinue;[PSCustomObject]@{Port=$c.LocalPort;Addr=$c.LocalAddress;Pid=$c.OwningProcess;Name=if($p){$p.ProcessName}else{'INCONNU'};Path=if($p){$p.Path}else{'?'}}};$r|ConvertTo-Json -Compress";const data=await psJSON(cmd,15000,[]);if(data._error)return[];return(Array.isArray(data)?data:[data]).map(p=>({...p,Risk:portRisk(p.Port,p.Addr)}));}
async function getConnections(){const cmd="$r=Get-NetTCPConnection -State Established|Where-Object{$_.RemoteAddress -notmatch '^(10\\.|172\\.(1[6-9]|2[0-9]|3[01])\\.|192\\.168\\.|127\\.|::1)'}|Select-Object -First 40;$out=foreach($c in $r){$p=Get-Process -Id $c.OwningProcess -EA SilentlyContinue;[PSCustomObject]@{Remote=$c.RemoteAddress;RemotePort=$c.RemotePort;LocalPort=$c.LocalPort;Pid=$c.OwningProcess;Name=if($p){$p.ProcessName}else{'INCONNU'}}};$out|ConvertTo-Json -Compress";return psJSON(cmd,15000,[]);}
async function getStartup(){const cmd="$items=@();@('HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run','HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run')|ForEach-Object{$key=$_;$props=Get-ItemProperty -Path $key -EA SilentlyContinue;if($props){$props.PSObject.Properties|Where-Object{$_.Name -notmatch '^PS'}|ForEach-Object{$items+=[PSCustomObject]@{Name=$_.Name;Path=$_.Value;Key=$key}}}};$items|ConvertTo-Json -Compress";return psJSON(cmd,10000,[]);}
async function getEvents(){const cmd="$evts=@();$sm=Get-WinEvent -FilterHashtable @{LogName='Microsoft-Windows-Sysmon/Operational';Id=@(1,3,7,11,12,13)} -MaxEvents 20 -EA SilentlyContinue;$sn=@{1='PROCESSUS CREE';3='CONNEXION RESEAU';7='DLL CHARGEE';11='FICHIER CREE';12='REGISTRE';13='REGISTRE MODIFIE'};foreach($e in $sm){$m=$e.Message;if($m.Length -gt 200){$m=$m.Substring(0,200)};$evts+=[PSCustomObject]@{Source='SYSMON';Time=$e.TimeCreated.ToString('HH:mm:ss');Id=$e.Id;Type=$sn[[int]$e.Id];Msg=$m}};$sc=Get-WinEvent -FilterHashtable @{LogName='Security';Id=@(4625,4720,4732,4698)} -MaxEvents 10 -EA SilentlyContinue;$secn=@{4625='ECHEC LOGIN';4720='COMPTE CREE';4732='GROUPE MODIFIE';4698='TACHE PLANIFIEE'};foreach($e in $sc){$m=$e.Message;if($m.Length -gt 200){$m=$m.Substring(0,200)};$evts+=[PSCustomObject]@{Source='SECURITE';Time=$e.TimeCreated.ToString('HH:mm:ss');Id=$e.Id;Type=$secn[[int]$e.Id];Msg=$m}};$evts|Sort-Object Time -Descending|Select-Object -First 30|ConvertTo-Json -Compress";return psJSON(cmd,15000,[]);}
async function getAdGuard(){const cmd="$r=[PSCustomObject]@{ServiceRunning=$false;DnsPort53Open=$false;SystemDnsIsLocal=$false;SystemDns=@()};$svc=Get-Service AdGuardHome -EA SilentlyContinue;if($svc){$r.ServiceRunning=($svc.Status -eq 'Running')};$r.DnsPort53Open=($null -ne (Get-NetTCPConnection -State Listen -EA SilentlyContinue|Where-Object{$_.LocalPort -eq 53}));$dns=(Get-DnsClientServerAddress -AddressFamily IPv4 -EA SilentlyContinue|Where-Object{$_.ServerAddresses.Count -gt 0}|Select-Object -First 1).ServerAddresses;if($dns){$r.SystemDns=$dns;$r.SystemDnsIsLocal=($dns -contains '127.0.0.1')};$r|ConvertTo-Json -Compress";return psJSON(cmd,10000,{ServiceRunning:false,DnsPort53Open:false,SystemDnsIsLocal:false,SystemDns:[]});}
async function getSuricata(){const eveFile=config.suricataEvePath;const result={running:false,rulesLoaded:0,packetsToday:0,alertsToday:[],alertCount:0,kernelDrops:0,uptime:0};const status=await psExec("$p=Get-Process suricata -EA SilentlyContinue;if($p){'RUNNING'}else{'STOPPED'}",5000);result.running=status==='RUNNING';if(!fs.existsSync(eveFile))return result;try{const stat=fs.statSync(eveFile),readSize=Math.min(stat.size,config.suricataMaxReadBytes);const buffer=Buffer.alloc(readSize),fd=fs.openSync(eveFile,'r');fs.readSync(fd,buffer,0,readSize,Math.max(0,stat.size-readSize));fs.closeSync(fd);const text=buffer.toString('utf8'),firstNL=text.indexOf('\n');const lines=(firstNL>=0?text.substring(firstNL+1):text).split('\n').filter(Boolean);for(const line of lines){try{const e=JSON.parse(line);if(e.event_type==='stats'){result.packetsToday=e.stats?.decoder?.pkts||result.packetsToday;result.kernelDrops=e.stats?.capture?.kernel_drops||0;result.uptime=e.stats?.uptime||0;result.rulesLoaded=e.stats?.detect?.engines?.[0]?.rules_loaded||result.rulesLoaded;}if(e.event_type==='alert'){result.alertCount++;if(result.alertsToday.length<10)result.alertsToday.push({time:(e.timestamp||'').slice(11,19),sig:e.alert?.signature||'Unknown',category:e.alert?.category||'',severity:e.alert?.severity||3,src:e.src_ip||'',dst:e.dest_ip||''});}}catch{}}}catch(e){log('WARN','Suricata read fail',{error:e.message});}return result;}
async function getBackup(){const f=path.join(__dirname,'backup_status.json');if(fs.existsSync(f)){try{const age=(Date.now()-fs.statSync(f).mtimeMs)/60000;if(age<60)return JSON.parse(fs.readFileSync(f,'utf8').replace(/^\uFEFF/,''));}catch{}}return psJSON("$r=[PSCustomObject]@{vssCount=0;lastBackup=$null;lastBackupAge=$null;vssService=$false};$v=Get-Service VSS -EA SilentlyContinue;$r.vssService=($v -ne $null -and $v.Status -eq 'Running');$r|ConvertTo-Json -Compress",6000,{vssCount:0,lastBackup:null,lastBackupAge:null,vssService:false});}
const FIM_FILE=path.join(__dirname,'fim_baseline.json');const FIM_PATHS=['C:\\Windows\\System32\\cmd.exe','C:\\Windows\\System32\\powershell.exe','C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe','C:\\Windows\\System32\\net.exe','C:\\Windows\\System32\\net1.exe','C:\\Windows\\System32\\wscript.exe','C:\\Windows\\System32\\cscript.exe','C:\\Windows\\System32\\mshta.exe','C:\\Windows\\System32\\certutil.exe','C:\\Windows\\System32\\bitsadmin.exe','C:\\Windows\\System32\\regsvr32.exe','C:\\Windows\\System32\\rundll32.exe','C:\\Windows\\System32\\schtasks.exe','C:\\Windows\\System32\\drivers\\etc\\hosts'];
let fimBaseline={};let fimAlerts=[];
function loadFimBaseline(){try{if(fs.existsSync(FIM_FILE))fimBaseline=JSON.parse(fs.readFileSync(FIM_FILE,'utf8'));}catch{}}
function saveFimBaseline(){try{fs.writeFileSync(FIM_FILE,JSON.stringify(fimBaseline,null,2),'utf8');}catch{}}
async function checkFim(){if(!config.fimEnabled)return{alerts:[],filesMonitored:0,lastCheck:null};const alerts=[];const cmd=FIM_PATHS.map(p=>"$f='"+p.replace(/'/g,"''")+"';if(Test-Path $f){$h=(Get-FileHash $f -Algorithm SHA256 -EA SilentlyContinue).Hash;$s=(Get-Item $f -EA SilentlyContinue).Length;[PSCustomObject]@{Path=$f;Hash=$h;Size=$s}}else{[PSCustomObject]@{Path=$f;Hash='MISSING';Size=0}}").join(';')+'|ConvertTo-Json -Compress';const data=await psJSON(cmd,20000,[]);if(!Array.isArray(data))return{alerts:fimAlerts,filesMonitored:FIM_PATHS.length,lastCheck:new Date().toISOString()};const isNew=Object.keys(fimBaseline).length===0;for(const f of data){if(!f.Path||!f.Hash)continue;const prev=fimBaseline[f.Path];if(!prev){fimBaseline[f.Path]={hash:f.Hash,size:f.Size,firstSeen:new Date().toISOString()};if(!isNew&&f.Hash!=='MISSING'){const a={time:new Date().toISOString(),path:f.Path,type:'NEW',msg:'Nouveau fichier detecte'};alerts.push(a);fimAlerts.unshift(a);}}else if(prev.hash!==f.Hash){const a={time:new Date().toISOString(),path:f.Path,type:f.Hash==='MISSING'?'DELETED':'MODIFIED',oldHash:prev.hash,newHash:f.Hash,msg:f.Hash==='MISSING'?'Fichier systeme SUPPRIME':'Fichier systeme MODIFIE'};alerts.push(a);fimAlerts.unshift(a);log('ALERT','FIM: '+a.msg,{path:f.Path});fimBaseline[f.Path]={...prev,hash:f.Hash,size:f.Size,lastChange:new Date().toISOString()};}}if(fimAlerts.length>100)fimAlerts=fimAlerts.slice(0,100);saveFimBaseline();return{alerts:fimAlerts.slice(0,30),filesMonitored:data.length,lastCheck:new Date().toISOString(),newAlerts:alerts};}
const CANARY_DIR=config.canaryDir||path.join(__dirname,'canary_files');const CANARY_FILES=[{name:'Budget_2024.xlsx',size:2048},{name:'Passwords_backup.docx',size:1536},{name:'Company_Keys.pdf',size:3072},{name:'Client_Database.csv',size:4096},{name:'Financial_Report.xlsx',size:2560}];const CANARY_MAGIC='SENTINEL-CANARY-v3-';let canaryHashes={};let canaryTriggered=false;let canaryStatus={active:false,files:0,triggered:false,triggerTime:null,triggerFile:null};
function initCanary(){if(!config.canaryEnabled)return;try{if(!fs.existsSync(CANARY_DIR))fs.mkdirSync(CANARY_DIR,{recursive:true});for(const cf of CANARY_FILES){const fp=path.join(CANARY_DIR,cf.name);if(!fs.existsSync(fp)){fs.writeFileSync(fp,CANARY_MAGIC+crypto.randomBytes(cf.size).toString('base64'));}const hash=crypto.createHash('sha256').update(fs.readFileSync(fp)).digest('hex');canaryHashes[cf.name]=hash;}canaryStatus.active=true;canaryStatus.files=CANARY_FILES.length;log('INFO','Canary init',{count:CANARY_FILES.length});}catch(e){log('WARN','Canary fail',{error:e.message});}}
function checkCanary(){if(!config.canaryEnabled||!canaryStatus.active)return canaryStatus;try{for(const cf of CANARY_FILES){const fp=path.join(CANARY_DIR,cf.name);if(!fs.existsSync(fp)){canaryStatus.triggered=true;canaryStatus.triggerTime=new Date().toISOString();canaryStatus.triggerFile=cf.name;canaryStatus.reason='DELETED';log('ALERT','CANARY DELETED',{file:cf.name});return canaryStatus;}const hash=crypto.createHash('sha256').update(fs.readFileSync(fp)).digest('hex');if(canaryHashes[cf.name]&&hash!==canaryHashes[cf.name]){canaryStatus.triggered=true;canaryStatus.triggerTime=new Date().toISOString();canaryStatus.triggerFile=cf.name;canaryStatus.reason='MODIFIED';log('ALERT','CANARY MODIFIED',{file:cf.name});return canaryStatus;}}}catch(e){log('WARN','Canary check fail',{error:e.message});}return canaryStatus;}
async function getHardening(){if(!config.hardeningEnabled)return{score:0,max:0,checks:[]};const cmd="$c=@();$uac=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -EA SilentlyContinue).EnableLUA;$c+=[PSCustomObject]@{Name='UAC';Status=if($uac -eq 1){'OK'}else{'FAIL'};Detail=if($uac -eq 1){'Active'}else{'Off'}};$wu=try{(New-Object -ComObject Microsoft.Update.AutoUpdate).Results.LastSearchSuccessDate}catch{$null};$wuAge=if($wu){[math]::Round(((Get-Date)-$wu).TotalDays,0)}else{999};$c+=[PSCustomObject]@{Name='WinUpdate';Status=if($wuAge -lt 7){'OK'}elseif($wuAge -lt 30){'WARN'}else{'FAIL'};Detail=if($wu){$wuAge.ToString()+'j'}else{'?'}};$rdp=(Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server' -EA SilentlyContinue).fDenyTSConnections;$c+=[PSCustomObject]@{Name='RDP';Status=if($rdp -eq 1){'OK'}else{'FAIL'};Detail=if($rdp -eq 1){'Off'}else{'ON'}};$bl=try{(Get-BitLockerVolume -MountPoint 'C:' -EA Stop).ProtectionStatus}catch{'Off'};$c+=[PSCustomObject]@{Name='BitLocker';Status=if($bl -eq 'On' -or $bl -eq 1){'OK'}else{'FAIL'};Detail=if($bl -eq 'On' -or $bl -eq 1){'On'}else{'Off'}};$g=(Get-LocalUser -Name 'Guest' -EA SilentlyContinue).Enabled;$c+=[PSCustomObject]@{Name='Guest';Status=if($g -eq $false){'OK'}else{'FAIL'};Detail=if($g -eq $false){'Off'}else{'ON'}};$s1=try{(Get-SmbServerConfiguration -EA Stop).EnableSMB1Protocol}catch{$false};$c+=[PSCustomObject]@{Name='SMBv1';Status=if($s1 -eq $false){'OK'}else{'FAIL'};Detail=if($s1 -eq $false){'Off'}else{'ON'}};$ep=Get-ExecutionPolicy;$c+=[PSCustomObject]@{Name='PSPolicy';Status=if($ep -eq 'Restricted' -or $ep -eq 'AllSigned'){'OK'}elseif($ep -eq 'RemoteSigned'){'WARN'}else{'FAIL'};Detail=$ep.ToString()};$sb=try{Confirm-SecureBootUEFI -EA Stop}catch{$false};$c+=[PSCustomObject]@{Name='SecureBoot';Status=if($sb){'OK'}else{'WARN'};Detail=if($sb){'On'}else{'Off'}};$ad=@(Get-LocalGroupMember -Group 'Administrators' -EA SilentlyContinue).Count;$c+=[PSCustomObject]@{Name='Admins';Status=if($ad -le 2){'OK'}elseif($ad -le 3){'WARN'}else{'FAIL'};Detail=$ad.ToString()};$ap=(Get-ItemProperty 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\AutoplayHandlers' -EA SilentlyContinue).DisableAutoplay;$c+=[PSCustomObject]@{Name='AutoPlay';Status=if($ap -eq 1){'OK'}else{'WARN'};Detail=if($ap -eq 1){'Off'}else{'On'}};$c|ConvertTo-Json -Compress";const checks=await psJSON(cmd,20000,[]);if(!Array.isArray(checks))return{score:0,max:0,checks:[]};const ok=checks.filter(c=>c.Status==='OK').length;return{score:Math.round((ok/Math.max(checks.length,1))*100),max:100,checks,okCount:ok,totalCount:checks.length};}
